### ISSUE TITLE
general question about your experience building this project

### ISSUE THREAD

**Issue by ghost** [Imira-S-R/PasswordManager#1]
Hi @Imira-S-R  ,

Hope you are all well !

I would like to create a clone of [teampass](https://github.com/nilsteampassnet/TeamPass) a collaborative password manager, and I was wondering if you knew or can explain how to create a catalog of items, organised with an [animated tree view](https://github.com/embraceitmobile/animated_tree_view), and [flutter_rbac](https://github.com/wilpar/flutter_rbac) for managing roles and permissions. From your experience, what advices would you give me for neat architecture.

Thanks for any insights or inputs on that question.

teampass screeenshot:
![pf_tp_5](https://user-images.githubusercontent.com/1963546/143676762-88e5e5c0-6a3e-473f-adae-09d9ae274f18.png)

Cheers,
Luc

**Comment by Imira-S-R** [comment]
Hello @lucmichalski 👋
Sorry for the delayed response
Hope you are doing well,

I'm still a student learning Flutter, and I haven't implemented Role-based access control because I only wanted to make a simple password manager. I'm sorry, but I'm unable to assist you with that. You may, however, use this [package](https://pub.dev/packages/animated_tree_view) for Animated Tree View.

To have a clean architecture, the app must be simple & efficient, the code must be understandable, and the app must be well tested in order to reduce the amount of problems in the final product. These are some of the factors I consider while creating an app.

I hope this knowledge is useful to you.
Imira
